[package]
name = "ethereum-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "1.0.2", features = [
  "ws",
  "rustls",
] }
serde_json = "1.0.72"
serde = "1.0.131"
anyhow = "1.0.51"
